### ISSUE TITLE
remove series

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-example-twitter#14]
This is not needed https://github.com/fastify/fastify-example-twitter/blob/master/index.js#L42-L55, you can remove the callback passed to `next()` in the recent Fastify.

Something like:

```js
module.exports = async function (fastify, opts) {
  fastify
    .register(require('fastify-swagger'), swaggerOptions)
    .register(require('./user'), { prefix: '/api/user' }
   //...
}
```

**Comment by allevo** [comment]
#17
