### ISSUE TITLE
Question: Best way for context aware logs inside service

### ISSUE THREAD

**Issue by nileshmali** [fastify/fastify-example-twitter#3]
Hi,
I have a question around logging inside services. 
Let say I would want to log some statements inside user service and it should also contain context information like requestId which would help in debugging production applications.

Is it possible to add some example for this use case?

In other words passing the context information or req.log across all operations.

**Comment by mcollina** [comment]
fastify adds an id to each request, and its algorithm can be changes as well. https://github.com/fastify/fastify/blob/b29a9e3f2e9f564fb6e4198676c062be7b1ca0bf/fastify.js#L43 but it's not really well documented.

I've opened up a couple of issues to track progress:

https://github.com/fastify/fastify/issues/251
https://github.com/fastify/fastify/issues/250

**Comment by nileshmali** [comment]
@mcollina Thanks for quick reply.
I am aware of request id, but my point was lets take an example of [UserService](https://github.com/fastify/fastify-example-twitter/blob/init/server/user/UserService.js) from current repository and we want to log something inside method [search](https://github.com/fastify/fastify-example-twitter/blob/255ee7ea5310b5f15aaf96ae0e6c5051f87d30fc/server/user/UserService.js#L47) 
where to access requestId is by passing it as parameter from request handler and another could be something like [continuation-local-storage](https://www.npmjs.com/package/continuation-local-storage) or better [zone.js](https://github.com/angular/zone.js).
Now how to integrate this with fastify by not impacting performance? Any Ideas or Suggestions?

**Comment by allevo** [comment]
Hi @nileshmali and thank you for checking fastify and this example out!

This is a good question.
In my experience where're two ways:
- `UserService` constructor has the logger as parameter: you can build an instance every request. In this way your logs has tracked with the request id.
- each `UserService` method has the logger as first parameter.

I prefer the second because is more performant than first but it depends on your use case.

Anyway there's no a correct way. Only best practises.

**Comment by mcollina** [comment]
We are working to add a zipkin plugin.
That should help you in implementing that solution.

**Comment by nileshmali** [comment]
Thank you @mcollina @allevo.
Please let me know if you need any contributions I would be ready to help. I am already watching for "help wanted" label.

**Comment by mcollina** [comment]
I've added the label to some issues :)
